// app/edge-of-knowledge/hodge-conjecture-algebraicity-obstruction/page.tsx
// ============================================================
// EDGE OF KNOWLEDGE
// Hodge Conjecture — Algebraicity Obstruction
// Regime-bounded, non-actionable, non-advisory doctrine
// ============================================================
// This entry exposes an epistemic boundary.
// It does not propose constructions, proof strategies, or applications.
// ============================================================

import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "The Hodge Conjecture: The Algebraicity Obstruction | Edge of Knowledge",
  description:
    "A formal reduction identifying the shared hidden assumption underlying all major approaches to the Hodge Conjecture and the resulting epistemic limitation.",
  robots: {
    index: true,
    follow: true,
  },
};

export const dynamic = "force-static";

export default function HodgeConjectureAlgebraicityObstructionPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <article className="prose prose-neutral dark:prose-invert max-w-none">
        <h1>
          The Hodge Conjecture
          <br />
          and the Algebraicity Obstruction
        </h1>

        <p className="lead">
          <strong>
            This entry isolates the decisive epistemic limitation common to all
            known approaches to the Hodge Conjecture. It does not attempt proof,
            disproof, construction, or methodological guidance.
          </strong>
        </p>

        <p className="text-sm text-red-700 dark:text-red-400">
          <b>Boundary Notice:</b> This material is regime-bounded and
          non-actionable. It is not advice, instruction, or a proposal for
          mathematical research.
        </p>

        <h2>Precise Statement</h2>
        <p>
          Let <code>X</code> be a smooth, projective, complex algebraic variety of
          dimension <code>n</code>. The Hodge Conjecture asserts that every
          rational cohomology class of type <code>(p,p)</code> in{" "}
          <code>
            H
            <sup>2p</sup>(X, ℚ) ∩ H
            <sup>p,p</sup>(X, ℂ)
          </code>{" "}
          is a rational linear combination of cohomology classes of algebraic
          cycles of codimension <code>p</code> on <code>X</code>.
        </p>

        <p>Equivalently, every rational Hodge class is algebraic.</p>

        <h2>Scope</h2>
        <p>
          The conjecture applies to all smooth, projective varieties over ℂ and
          concerns the relationship between Hodge-theoretic (analytic) and
          algebraic (cycle-theoretic) origins of cohomology classes.
        </p>

        <h2>Dominant Historical Strategy Classes</h2>
        <ul>
          <li>
            <strong>Construction via Known Algebraic Cycles:</strong> explicit
            construction of cycles representing Hodge classes in special cases.
          </li>
          <li>
            <strong>Topological and Analytic Methods:</strong> mixed Hodge
            structures, variation of Hodge structure, and Lefschetz-type
            theorems.
          </li>
          <li>
            <strong>Reduction to Known Cases:</strong> extension from divisors
            (Lefschetz (1,1) theorem) and other proven regimes.
          </li>
          <li>
            <strong>Intermediate Jacobian and Normal Function Techniques:</strong>
            detection of obstructions via normal functions and regulator maps.
          </li>
        </ul>

        <h2>Core Hidden Assumption</h2>
        <p>
          All major approaches implicitly assume that the space of rational Hodge{" "}
          <code>(p,p)</code>-classes is exhaustively generated by algebraic
          cycles.
        </p>

        <p>
          In particular, it is assumed that there exist no “exotic” Hodge classes
          whose origin is analytic but not representable, even rationally, by
          algebraic cycles.
        </p>

        <h2>Why This Assumption Limits Progress</h2>
        <p>
          Known constructions of algebraic cycles do not scale uniformly across
          all varieties or all codimensions. No general obstruction theory
          excludes the existence of non-algebraic Hodge classes in higher
          codimension.
        </p>

        <ul>
          <li>
            Deformation and variation techniques may preserve Hodge type while
            obscuring algebraic realizability.
          </li>
          <li>Reduction arguments risk circularity outside the proven range.</li>
          <li>
            Normal function and regulator methods detect some obstructions but do
            not characterize all possibilities.
          </li>
          <li>
            There is no universal construction guaranteeing algebraicity for all
            Hodge classes.
          </li>
        </ul>

        <p>
          As a result, the conjecture may be true while remaining inaccessible to
          proof under current paradigms—or false in regimes not yet detectable.
        </p>

        <h2>Falsifiable Constraint</h2>
        <p>
          Any genuine resolution of the Hodge Conjecture must satisfy one of the
          following:
        </p>

        <ul>
          <li>
            <strong>Proof:</strong> provide a universal mechanism ensuring that
            every rational <code>(p,p)</code>-class arises from algebraic cycles
            for all smooth projective varieties.
          </li>
          <li>
            <strong>Counterexample:</strong> exhibit a specific variety and
            rational <code>(p,p)</code>-class that provably cannot be expressed
            as a rational combination of algebraic cycle classes.
          </li>
        </ul>

        <h2>Non-Conclusions</h2>
        <ul>
          <li>The conjecture is neither proved nor disproved.</li>
          <li>Results for divisors and special varieties do not generalize.</li>
          <li>
            Absence of known counterexamples does not imply universality.
          </li>
          <li>Analytic correspondence alone does not enforce algebraicity.</li>
        </ul>

        <h2>Canonical Classification</h2>
        <p>
          This entry is an <strong>Edge of Knowledge</strong> artifact. It
          delineates an epistemic boundary without proposing constructions,
          strategies, or applications.
        </p>

        <hr />

        <p className="text-sm text-neutral-400">
          Canonical · Public · Regime-bounded · Version 1.0
          <br />
          Updates require explicit revision. Silent modification invalidates the
          entry.
        </p>
      </article>
    </main>
  );
}
